spring:
  profiles: default
  application:
    name: currency-service
  datasource:
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    maximumPoolSize: 10
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_microservice?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF8&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
fixerio:
  service:
    url: http://data.fixer.io/api/latest?access_key=
    apikey: b11a888bc2599f57e7a37baf1f4fc410

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

server:
  port: ${PORT:2223}
