info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account: 
      path: /account/**
      serviceId: account-service
    customer: 
      path: /customer/**
      serviceId: customer-service
    currency:
      path: /v10/currency/**
      serviceId: currency-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

microservices:
  ta-accounts:
    host: http://localhost:8015



logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG